require("dotenv").config();
const express = require("express");
const path = require("node:path");

const crypto = require("node:crypto");
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const multer = require("multer");
const { Pool } = require("pg");

const ROOT = __dirname;
const PUBLIC_DIR = path.join(ROOT, "public");
const DEFAULT_PRODUCT_IMAGE = "/img/product01.png";
const DEFAULT_PRODUCT_IMAGE_FILE = path.join(
  PUBLIC_DIR,
  "img",
  "product01.png",
);



function postgresSql(sql) {
  let index = 0;
  return sql.replace(/\?/g, () => `$${++index}`);
}

class PostgresStatement {
  constructor(owner, sql, client = owner.pool) {
    this.owner = owner;
    this.sql = postgresSql(sql);
    this.client = client;
  }
  async all(...params) {
    const result = await this.client.query(this.sql, params);
    return result.rows;
  }
  async get(...params) {
    const rows = await this.all(...params);
    return rows[0];
  }
  async run(...params) {
    const sql =
      /^\s*INSERT\b/i.test(this.sql) && !/\bRETURNING\b/i.test(this.sql)
        ? `${this.sql} RETURNING id`
        : this.sql;
    const result = await this.client.query(sql, params);
    return {
      lastInsertRowid: result.rows[0]?.id ?? 0,
      changes: result.rowCount,
    };
  }
}

class PostgresDatabase {
  constructor(connectionString) {
    this.pool = new Pool({
      connectionString,
      ssl: { rejectUnauthorized: false },
    });
  }
  async init() {
    await this.pool.query("SELECT 1");
    return this;
  }
  async exec(sql) {
    return this.pool.query(sql);
  }
  prepare(sql) {
    return new PostgresStatement(this, sql);
  }
  async transaction(callback) {
    const client = await this.pool.connect();
    try {
      await client.query("BEGIN");
      const value = await callback({
        prepare: (sql) => new PostgresStatement(this, sql, client),
      });
      await client.query("COMMIT");
      return value;
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally {
      client.release();
    }
  }
  async close() {
    await this.pool.end();
  }
}



const PORT = Number(process.env.PORT || 3000);
const DATABASE_URL = process.env.DATABASE_URL;
const JWT_SECRET = process.env.JWT_SECRET;
const ADMIN_EMAIL = process.env.ADMIN_EMAIL?.trim().toLowerCase();
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;

if (!Number.isInteger(PORT) || PORT <= 0) {
  throw new Error("PORT harus berupa angka positif.");
}
if (!DATABASE_URL || !JWT_SECRET || !ADMIN_EMAIL || !ADMIN_PASSWORD) {
  throw new Error(
    "Konfigurasi environment belum lengkap. Isi DATABASE_URL, JWT_SECRET, ADMIN_EMAIL, dan ADMIN_PASSWORD.",
  );
}
const db = new PostgresDatabase(DATABASE_URL);
const ready = db.init().then(async () => {
  await db.exec(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS products (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      description TEXT NOT NULL DEFAULT '',
      category TEXT NOT NULL DEFAULT 'aksesori',
      price INTEGER NOT NULL CHECK (price >= 0),
      old_price INTEGER,
      stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
      image TEXT NOT NULL DEFAULT '/img/product01.png',
      is_featured INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS image_uploads (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      public_path TEXT NOT NULL UNIQUE,
      file_id TEXT NOT NULL UNIQUE,
      file_url TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER,
      customer_name TEXT NOT NULL,
      email TEXT NOT NULL,
      address TEXT NOT NULL,
      city TEXT NOT NULL,
      country TEXT NOT NULL,
      zip_code TEXT NOT NULL,
      telephone TEXT NOT NULL,
      payment_method TEXT NOT NULL,
      notes TEXT NOT NULL DEFAULT '',
      total INTEGER NOT NULL CHECK (total >= 0),
      status TEXT NOT NULL DEFAULT 'pending',
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    );
    CREATE TABLE IF NOT EXISTS order_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id INTEGER NOT NULL,
      product_id INTEGER,
      product_name TEXT NOT NULL,
      price INTEGER NOT NULL,
      quantity INTEGER NOT NULL CHECK (quantity > 0),
      FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
      FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
    );
  `);
  const seedProducts = [
    [
      "Laptop Pro 14 inci",
      "laptop-pro-14-inci",
      "Laptop tipis untuk pekerjaan dan hiburan.",
      "laptop",
      14999000,
      15999000,
      12,
      "/img/product01.png",
      1,
    ],
    [
      "Headphone Nirkabel",
      "headphone-nirkabel",
      "Audio jernih dengan koneksi nirkabel stabil.",
      "aksesori",
      899000,
      1099000,
      35,
      "/img/product02.png",
      1,
    ],
    [
      "Laptop Ultra Slim",
      "laptop-ultra-slim",
      "Performa cepat dalam bodi ringan.",
      "laptop",
      12999000,
      13999000,
      9,
      "/img/product03.png",
      1,
    ],
    [
      "Tablet Android 10 inci",
      "tablet-android-10-inci",
      "Tablet serbaguna untuk aktivitas sehari-hari.",
      "smartphone",
      3299000,
      null,
      20,
      "/img/product04.png",
      0,
    ],
    [
      "Kamera Mirrorless",
      "kamera-mirrorless",
      "Kamera ringkas untuk foto dan video berkualitas.",
      "kamera",
      7499000,
      7999000,
      7,
      "/img/product05.png",
      1,
    ],
  ];
  if (Number((await db.prepare("SELECT COUNT(*) AS count FROM products").get()).count) === 0) {
    await db.transaction(async (tx) => {
      const insert = tx.prepare(
        "INSERT INTO products (name, slug, description, category, price, old_price, stock, image, is_featured) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
      );
      for (const product of seedProducts) await insert.run(...product);
    });
  }
  const admin = await db
    .prepare("SELECT id, password_hash, role FROM users WHERE email = ?")
    .get(ADMIN_EMAIL);
  if (!admin) {
    await db.prepare(
      "INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, ?)",
    ).run(
      "Administrator",
      ADMIN_EMAIL,
      bcrypt.hashSync(ADMIN_PASSWORD, 12),
      "admin",
    );
  } else if (
    admin.role !== "admin" ||
    !bcrypt.compareSync(ADMIN_PASSWORD, admin.password_hash)
  ) {
    await db.prepare(
      "UPDATE users SET password_hash = ?, role = 'admin' WHERE id = ?",
    ).run(bcrypt.hashSync(ADMIN_PASSWORD, 12), admin.id);
  }
  return db;
});

const app = express();
app.disable("x-powered-by");
app.use(express.json({ limit: "1mb" }));
app.use(express.urlencoded({ extended: true }));
app.get("/uploads/:filename", async (req, res, next) => {
  const filename = path.basename(req.params.filename);
  if (filename !== req.params.filename) return res.status(404).end();
  try {
    const publicPath = `/uploads/${filename}`;
    const uploaded = await db
      .prepare("SELECT file_url FROM image_uploads WHERE public_path = ?")
      .get(publicPath);
    if (!uploaded) return res.sendFile(DEFAULT_PRODUCT_IMAGE_FILE);
    let remote;
    try {
      remote = await imageKitFetch(uploaded.file_url, {}, "delivery");
    } catch (error) {
      console.error(error.message);
      return res.sendFile(DEFAULT_PRODUCT_IMAGE_FILE);
    }
    if (!remote.ok || !remote.body)
      return res.sendFile(DEFAULT_PRODUCT_IMAGE_FILE);
    const body = Buffer.from(await remote.arrayBuffer());
    if (!body.length) return res.sendFile(DEFAULT_PRODUCT_IMAGE_FILE);
    res.set(
      "Content-Type",
      remote.headers.get("content-type") || "application/octet-stream",
    );
    res.set("Cache-Control", "public, max-age=31536000, immutable");
    res.send(body);
  } catch (error) {
    next(error);
  }
});
app.use((req, res, next) => {
  const blocked =
    /^\/(?:data|server\.js|package(?:\.json|-lock\.json)?|scripts)(?:\/|$)/i;
  if (blocked.test(req.path) || req.path.startsWith("/."))
    return res.status(404).end();
  next();
});
app.use(express.static(PUBLIC_DIR, { index: "index.html" }));

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024 },
  fileFilter: (_req, file, cb) =>
    cb(
      null,
      new Set(["image/jpeg", "image/png", "image/webp", "image/gif"]).has(
        file.mimetype,
      ),
    ),
});
const IMAGEKIT_PRIVATE_KEY = process.env.IMAGEKIT_PRIVATE_KEY?.trim();
const IMAGEKIT_FOLDER =
  process.env.IMAGEKIT_FOLDER?.trim() || "/falstore/products";
const IMAGEKIT_UPLOAD_URL = "https://upload.imagekit.io/api/v1/files/upload";
const IMAGEKIT_API_URL = "https://api.imagekit.io/v1/files";
async function imageKitFetch(url, options, operation) {
  try {
    return await fetch(url, options);
  } catch (error) {
    const code = error.cause?.code || error.code || "NETWORK_ERROR";
    const wrapped = new Error(`ImageKit ${operation} gagal diakses (${code}).`);
    wrapped.statusCode = 503;
    throw wrapped;
  }
}

function imageKitHeaders() {
  if (!IMAGEKIT_PRIVATE_KEY)
    throw new Error("IMAGEKIT_PRIVATE_KEY belum dikonfigurasi.");
  return {
    Authorization: `Basic ${Buffer.from(`${IMAGEKIT_PRIVATE_KEY}:`).toString(
      "base64",
    )}`,
  };
}
async function uploadToImageKit(file) {
  const extension = path.extname(file.originalname).toLowerCase() || ".bin";
  const filename = `${crypto.randomUUID()}${extension}`;
  const form = new FormData();
  form.append("file", new Blob([file.buffer], { type: file.mimetype }), filename);
  form.append("fileName", filename);
  form.append("folder", IMAGEKIT_FOLDER);
  form.append("useUniqueFileName", "false");
  const response = await imageKitFetch(
    IMAGEKIT_UPLOAD_URL,
    {
      method: "POST",
      headers: imageKitHeaders(),
      body: form,
    },
    "upload",
  );

  const result = await response.json().catch(() => null);
  if (!response.ok || !result?.url || !result?.fileId)
    throw new Error(
      `Upload ImageKit gagal: ${result?.message || response.statusText}`,
    );
  const publicPath = `/uploads/${crypto.randomUUID()}${extension}`;
  await db
    .prepare(
      "INSERT INTO image_uploads (public_path, file_id, file_url) VALUES (?, ?, ?)",
    )
    .run(publicPath, result.fileId, result.url);
  return {
    publicPath,
    imageKitUrl: result.url,
    filename,
    size: file.size,
  };
}

function publicUser(user) {
  return {
    id: user.id,
    name: user.name,
    email: user.email,
    role: user.role,
    createdAt: user.created_at,
  };
}
async function productImage(image) {
  const value = String(image || "").trim();
  if (!value.startsWith("/uploads/")) return value || DEFAULT_PRODUCT_IMAGE;
  const filename = path.basename(value);
  if (!filename || value !== `/uploads/${filename}`)
    return DEFAULT_PRODUCT_IMAGE;
  const uploaded = await db
    .prepare("SELECT file_url FROM image_uploads WHERE public_path = ?")
    .get(value);
  return uploaded?.file_url || DEFAULT_PRODUCT_IMAGE;
}
async function publicProduct(product) {
  const { sales_count, ...rest } = product;
  return {
    ...rest,
    image: await productImage(rest.image),
    salesCount: Number(sales_count || 0),
    isFeatured: Boolean(product.is_featured),
    createdAt: product.created_at,
    updatedAt: product.updated_at,
  };
}
function signUser(user) {
  return jwt.sign({ sub: user.id, role: user.role }, JWT_SECRET, {
    expiresIn: "7d",
  });
}
function auth(required = true) {
  return async (req, res, next) => {
    const token = (req.headers.authorization || "").replace(/^Bearer\s+/i, "");
    if (!token)
      return required
        ? res.status(401).json({ error: "Autentikasi diperlukan." })
        : next();
    try {
      const payload = jwt.verify(token, JWT_SECRET);
      const user = await db
        .prepare(
          "SELECT id, name, email, role, created_at FROM users WHERE id = ?",
        )
        .get(payload.sub);
      if (!user) return res.status(401).json({ error: "Sesi tidak valid." });
      req.user = user;
      next();
    } catch {
      return res
        .status(401)
        .json({ error: "Token tidak valid atau sudah kedaluwarsa." });
    }
  };
}
function adminOnly(req, res, next) {
  if (req.user?.role !== "admin")
    return res.status(403).json({ error: "Akses admin diperlukan." });
  next();
}
function validateProduct(body) {
  const name = String(body.name || "").trim();
  const category = String(body.category || "aksesori")
    .trim()
    .toLowerCase();
  const price = Number(body.price);
  const oldPrice =
    body.oldPrice === "" || body.oldPrice == null
      ? null
      : Number(body.oldPrice);
  const stock = Number(body.stock);
  if (
    !name ||
    !Number.isInteger(price) ||
    price < 0 ||
    (oldPrice !== null && (!Number.isInteger(oldPrice) || oldPrice < 0)) ||
    !Number.isInteger(stock) ||
    stock < 0
  )
    return {
      error:
        "Nama, harga, harga lama, dan stok harus diisi dengan angka yang valid.",
    };
  return {
    value: {
      name,
      slug: String(body.slug || name)
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, ""),
      description: String(body.description || "").trim(),
      category,
      price,
      oldPrice,
      stock,
      image: String(body.image || "/img/product01.png").trim(),
      isFeatured: Boolean(body.isFeatured),
    },
  };
}
async function removeUploadedImage(image) {
  if (
    !image?.startsWith("/uploads/") &&
    !image?.startsWith("https://")
  )
    return;
  const uploaded = await db
    .prepare(
      "SELECT file_id FROM image_uploads WHERE public_path = ? OR file_url = ?",
    )
    .get(image, image);
  if (!uploaded) return;
  try {
    const response = await imageKitFetch(
      `${IMAGEKIT_API_URL}/${encodeURIComponent(uploaded.file_id)}`,
      { method: "DELETE", headers: imageKitHeaders() },
      "delete",
    );
    if (!response.ok && response.status !== 404)
      throw new Error(`Penghapusan ImageKit gagal: ${response.statusText}`);
    await db
      .prepare(
        "DELETE FROM image_uploads WHERE public_path = ? OR file_url = ?",
      )
      .run(image, image);
  } catch (error) {
    console.error(error.message);
  }
}

app.get("/api/health", (_req, res) =>
  res.json({ ok: true, service: "falstore-api" }),
);
app.post("/api/auth/register", async (req, res, next) => {
  try {
    const name = String(req.body.name || "").trim();
    const email = String(req.body.email || "")
      .trim()
      .toLowerCase();
    const password = String(req.body.password || "");
    if (name.length < 2 || !/^\S+@\S+\.\S+$/.test(email) || password.length < 8)
      return res.status(400).json({
        error:
          "Nama, email valid, dan kata sandi minimal 8 karakter diperlukan.",
      });
    const result = await db
      .prepare(
        "INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, ?)",
      )
      .run(name, email, bcrypt.hashSync(password, 12), "customer");
    const user = await db
      .prepare(
        "SELECT id, name, email, role, created_at FROM users WHERE id = ?",
      )
      .get(result.lastInsertRowid);
    res.status(201).json({ token: signUser(user), user: publicUser(user) });
  } catch (error) {
    if (String(error.message).includes("UNIQUE"))
      return res.status(409).json({ error: "Email sudah terdaftar." });
    next(error);
  }
});
app.post("/api/auth/login", async (req, res, next) => {
  try {
    const email = String(req.body.email || "")
      .trim()
      .toLowerCase();
    const password = String(req.body.password || "");
    const user = await db
      .prepare(
        "SELECT id, name, email, password_hash, role, created_at FROM users WHERE email = ?",
      )
      .get(email);
    if (!user || !bcrypt.compareSync(password, user.password_hash))
      return res.status(401).json({ error: "Email atau kata sandi salah." });
    res.json({ token: signUser(user), user: publicUser(user) });
  } catch (error) {
    next(error);
  }
});
app.get("/api/auth/me", auth(), (req, res) =>
  res.json({ user: publicUser(req.user) }),
);

app.get("/api/products", async (req, res, next) => {
  try {
    const params = [];
    const conditions = [];
    if (req.query.category) {
      conditions.push("p.category = ?");
      params.push(String(req.query.category).toLowerCase());
    }
    if (req.query.search) {
      conditions.push("(p.name ILIKE ? OR p.description ILIKE ?)");
      const q = `%${String(req.query.search)}%`;
      params.push(q, q);
    }
    if (req.query.featured === "1") conditions.push("p.is_featured = 1");
    const parsePrice = (value) => {
      if (value == null || value === "") return null;
      const price = Number(value);
      return Number.isInteger(price) && price >= 0 ? price : null;
    };
    const minPrice = parsePrice(req.query.minPrice);
    const maxPrice = parsePrice(req.query.maxPrice);
    if (minPrice !== null) {
      conditions.push("p.price >= ?");
      params.push(minPrice);
    }
    if (maxPrice !== null) {
      conditions.push("p.price <= ?");
      params.push(maxPrice);
    }
    const where = conditions.length ? `WHERE ${conditions.join(" AND ")}` : "";
    const sort = String(req.query.sort || "latest");
    const popular = sort === "popular";
    const select = popular
      ? "SELECT p.*, COALESCE(SUM(oi.quantity), 0) AS sales_count FROM products p LEFT JOIN order_items oi ON oi.product_id = p.id"
      : "SELECT p.* FROM products p";
    const order =
      sort === "price_asc"
        ? "ORDER BY p.price ASC, p.id DESC"
        : sort === "price_desc"
          ? "ORDER BY p.price DESC, p.id DESC"
          : popular
            ? "ORDER BY sales_count DESC, p.created_at DESC, p.id DESC"
            : "ORDER BY p.created_at DESC, p.id DESC";
    const limit =
      Number.isInteger(Number(req.query.limit)) && Number(req.query.limit) > 0
        ? Math.min(Number(req.query.limit), 50)
        : null;
    const sql = `${select} ${where} ${popular ? "GROUP BY p.id" : ""} ${order}${limit ? " LIMIT ?" : ""}`;
    if (limit) params.push(limit);
    const products = await Promise.all(
      (await db.prepare(sql).all(...params)).map(publicProduct),
    );
    res.json({ products });
  } catch (error) {
    next(error);
  }
});
app.get("/api/products/:idOrSlug", async (req, res, next) => {
  try {
    const key = req.params.idOrSlug;
    const product = /^\d+$/.test(key)
      ? await db.prepare("SELECT * FROM products WHERE id = ?").get(Number(key))
      : await db.prepare("SELECT * FROM products WHERE slug = ?").get(key);
    if (!product)
      return res.status(404).json({ error: "Produk tidak ditemukan." });
    res.json({ product: await publicProduct(product) });
  } catch (error) {
    next(error);
  }
});

app.use("/api/admin", auth(), adminOnly);
app.get("/api/admin/stats", async (_req, res, next) => {
  try {
    const [products, customers, orders, revenue] = await Promise.all([
      db.prepare("SELECT COUNT(*)::int AS count FROM products").get(),
      db
        .prepare("SELECT COUNT(*)::int AS count FROM users WHERE role = 'customer'")
        .get(),
      db.prepare("SELECT COUNT(*)::int AS count FROM orders").get(),
      db
        .prepare(
          "SELECT COALESCE(SUM(total), 0)::int AS total FROM orders WHERE status != 'cancelled'",
        )
        .get(),
    ]);
    res.json({
      stats: {
        products: products.count,
        customers: customers.count,
        orders: orders.count,
        revenue: revenue.total,
      },
    });
  } catch (error) {
    next(error);
  }
});
app.get("/api/admin/products", async (_req, res, next) => {
  try {
    const products = await db
      .prepare("SELECT * FROM products ORDER BY id DESC")
      .all();
    res.json({ products: await Promise.all(products.map(publicProduct)) });

  } catch (error) {
    next(error);
  }
});
app.post("/api/admin/products", async (req, res, next) => {
  try {
    const parsed = validateProduct(req.body);
    if (parsed.error) return res.status(400).json({ error: parsed.error });
    const p = parsed.value;
    const result = await db
      .prepare(
        "INSERT INTO products (name, slug, description, category, price, old_price, stock, image, is_featured, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)",
      )
      .run(
        p.name,
        p.slug,
        p.description,
        p.category,
        p.price,
        p.oldPrice,
        p.stock,
        p.image,
        p.isFeatured ? 1 : 0,
      );
    res.status(201).json({
      product: await publicProduct(
        await db
          .prepare("SELECT * FROM products WHERE id = ?")
          .get(result.lastInsertRowid),
      ),
    });
  } catch (error) {
    if (String(error.message).includes("UNIQUE"))
      return res.status(409).json({ error: "Slug produk sudah digunakan." });
    next(error);
  }
});
app.put("/api/admin/products/:id", async (req, res, next) => {
  try {
    const current = await db
      .prepare("SELECT * FROM products WHERE id = ?")
      .get(Number(req.params.id));
    if (!current)
      return res.status(404).json({ error: "Produk tidak ditemukan." });
    const parsed = validateProduct({
      ...current,
      ...req.body,
      oldPrice: req.body.oldPrice ?? current.old_price,
      isFeatured: req.body.isFeatured ?? Boolean(current.is_featured),
    });
    if (parsed.error) return res.status(400).json({ error: parsed.error });
    const p = parsed.value;
    await db.prepare(
      "UPDATE products SET name = ?, slug = ?, description = ?, category = ?, price = ?, old_price = ?, stock = ?, image = ?, is_featured = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
    ).run(
      p.name,
      p.slug,
      p.description,
      p.category,
      p.price,
      p.oldPrice,
      p.stock,
      p.image,
      p.isFeatured ? 1 : 0,
      current.id,
    );
    if (current.image !== p.image) await removeUploadedImage(current.image);
    res.json({
      product: await publicProduct(
        await db.prepare("SELECT * FROM products WHERE id = ?").get(current.id),
      ),
    });
  } catch (error) {
    if (String(error.message).includes("UNIQUE"))
      return res.status(409).json({ error: "Slug produk sudah digunakan." });
    next(error);
  }
});
app.delete("/api/admin/products/:id", async (req, res, next) => {
  try {
    const product = await db
      .prepare("SELECT * FROM products WHERE id = ?")
      .get(Number(req.params.id));
    if (!product)
      return res.status(404).json({ error: "Produk tidak ditemukan." });
    await db.prepare("DELETE FROM products WHERE id = ?").run(product.id);
    await removeUploadedImage(product.image);
    res.status(204).end();
  } catch (error) {
    next(error);
  }
});
app.post(
  "/api/admin/uploads/image",
  upload.single("image"),
  async (req, res, next) => {
    if (!req.file)
      return res.status(400).json({
        error: "File gambar wajib diunggah (JPG, PNG, WEBP, atau GIF).",
      });
    try {
      const uploaded = await uploadToImageKit(req.file);
      res.status(201).json({
        url: uploaded.imageKitUrl,
        path: uploaded.publicPath,
        filename: uploaded.filename,
        size: uploaded.size,
      });
    } catch (error) {
      next(error);
    }
  },
);
app.get("/api/admin/orders", async (_req, res, next) => {
  try {
    res.json({
      orders: await db
        .prepare(
          "SELECT o.*, u.name AS account_name FROM orders o LEFT JOIN users u ON u.id = o.user_id ORDER BY o.id DESC",
        )
        .all(),
    });
  } catch (error) {
    next(error);
  }
});

app.post("/api/orders", auth(), async (req, res, next) => {
  try {
    const {
      customerName,
      email,
      address,
      city,
      country,
      zipCode,
      telephone,
      paymentMethod,
      notes = "",
      items,
    } = req.body;
    if (
      !customerName ||
      !email ||
      !address ||
      !city ||
      !country ||
      !zipCode ||
      !telephone ||
      !paymentMethod ||
      !Array.isArray(items) ||
      !items.length
    )
      return res.status(400).json({ error: "Data checkout belum lengkap." });
    const requested = items
      .map((item) => ({ id: Number(item.id), quantity: Number(item.quantity) }))
      .filter(
        (item) =>
          Number.isInteger(item.id) &&
          Number.isInteger(item.quantity) &&
          item.quantity > 0,
      );
    if (!requested.length)
      return res.status(400).json({ error: "Item pesanan tidak valid." });
    const products = await Promise.all(
      requested.map(async (item) => ({
        ...item,
        product: await db
          .prepare("SELECT * FROM products WHERE id = ?")
          .get(item.id),
      })),
    );
    if (
      products.some((item) => !item.product || item.quantity > item.product.stock)
    )
      return res
        .status(400)
        .json({ error: "Produk tidak tersedia atau stok tidak mencukupi." });
    const total = products.reduce(
      (sum, item) => sum + item.product.price * item.quantity,
      0,
    );
    const orderId = await db.transaction(async (tx) => {
      const order = await tx
        .prepare(
          "INSERT INTO orders (user_id, customer_name, email, address, city, country, zip_code, telephone, payment_method, notes, total) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        )
        .run(
          req.user.id,
          String(customerName),
          String(email),
          String(address),
          String(city),
          String(country),
          String(zipCode),
          String(telephone),
          String(paymentMethod),
          String(notes),
          total,
        );
      const addItem = tx.prepare(
        "INSERT INTO order_items (order_id, product_id, product_name, price, quantity) VALUES (?, ?, ?, ?, ?)",
      );
      const reduceStock = tx.prepare(
        "UPDATE products SET stock = stock - ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
      );
      for (const item of products) {
        await addItem.run(
          order.lastInsertRowid,
          item.product.id,
          item.product.name,
          item.product.price,
          item.quantity,
        );
        await reduceStock.run(item.quantity, item.product.id);
      }
      return order.lastInsertRowid;
    });
    res.status(201).json({ orderId, total });
  } catch (error) {
    next(error);
  }
});

app.use("/api", (_req, res) =>
  res.status(404).json({ error: "Endpoint tidak ditemukan." }),
);
app.use((error, _req, res, _next) => {
  console.error(error);
  res
    .status(Number(error.statusCode) || 500)
    .json({
      error:
        Number(error.statusCode) === 503
          ? "Layanan gambar sedang tidak dapat diakses."
          : "Terjadi kesalahan pada server.",
    });
});

async function start() {
  await ready;
  return app.listen(PORT, () =>
    console.log(`Falstore berjalan di http://localhost:${PORT}`),
  );
}
if (require.main === module) start();
module.exports = { app, db, ready, start };
